# Generated by Django 4.2.8 on 2024-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.ManyToManyField(blank=True, default='Нет автора', to='book.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='book',
            field=models.ManyToManyField(blank=True, default='Нет книги', to='book.book', verbose_name='Книга'),
        ),
    ]
